# Site settings
title: Blackman Solutions
description: by Aaron Blackman, MBA & App Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "https://akblackman.github.io/devsite/" # baseurl of site

# User settings
username: Aaron Blackman
user_description: Business Model Expert | iOS, Android & Web App Developer.
user_title: Executive MBA & App Developer
email: aaron@blackman-solutions.com
github_username:  akblackman

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
