# Site settings
title: Blackman Solutions
description: Business Consulting & x-Platform App Development
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "https://akblackman.github.io/devsite/" # baseurl of site

# User settings
username: Blackman Solutions
user_description: Business Consulting & x-Platform App Development
user_title: Business Consulting & x-Platform App Development
email: info@blackman-solutions.com
github_username:  akblackman

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
